### PR TITLE
Avoid rebasing in remote sync strategy

### PR DESCRIPTION
**Pull request by megawac**
This should avoid the constant "merge branch" in pull requests. 
E.g. https://github.com/jsdelivr/jsdelivr/pull/5330#issuecomment-112612854

/cc @UnbounDev

### CODE REVIEW

**Comment by megawac** [comment]
I'm just going to merge this (@jimaek)

**Comment by jimaek** [comment]
Tagged new version,  thank you

**Comment by megawac** [comment]
Can you tag it on npm

**Comment by megawac** [comment]
```sh
npm version minor
npm publish
git push origin --follow-tags
```

**Comment by jimaek** [comment]
Not from mobile, maybe Austin can.

**Comment by megawac** [comment]
I'm pretty sure only you and @aleksandara can

**Comment by jimaek** [comment]
Yeah,  we need to add you as contributors as well. 
I can only do it on Monday

**Pull request merged**
